### ISSUE TITLE
mdcat panics if image title is in two lines

### ISSUE THREAD

**Issue by laoshaw** [swsnr/mdcat#194] opened 2021-11-16 04:05 UTC
Not quite sure if this is a mdcat bug:  if I split the image line into two lines as below, run `mdcat test.md` under kitty will abort as shown below.

test.md

```
![
](my.png)
```
run `mdcat test.md` it will report below errors:

```
thread 'main' panicked at 'Event SoftBreak impossible in state Stacked(StateStack { top_level: TopLevelAttrs { margin_before: Margin }, states: [Inline(InlineText, InlineAttrs { style: Style {}, indent: 0 })] }, RenderedImage)
```

put test.md above into one line it works fine.

**Comment by lunaryorn** [comment] 2021-11-16 08:36
It probably is; I've never seen this before and it doesn't seem to be part of the common mark test suite, so I don't think mdcat handles this.

I'll perhaps fix this at some point but it'll take time; to me this is a weird corner case so until I actually hit a document with this it's pretty low on my priority list.

If you need to have this fixed any time soon please do open a pull request.

**Comment by laoshaw** [comment] 2021-11-16 12:42
I agree, just add why this happens: pandoc converts html to markdown and if an image has a long line, pandoc will break it two into two lines and cause mdcat to misbehave, e.g.

```
! [ this is a super long line whatever asdf asdfsdafsdf fsdfsdfsf sfsdf  sfsdfs sdfsfsdf
and it has to continue to next time](you-image-here)
```

**Comment by norman-abramovitz** [comment] 2022-12-24 03:42
On the macOS M1 environment, even a simple image does not display using kitty installed using brew.  
It displays the base64 of the image instead of the image.  iterm2 works just fine.

The error log shows
[357 19:35:08.151068] [PARSE ERROR] OSC sequence too long, truncating.
[357 19:35:08.151117] [PARSE ERROR] Unknown OSC code: 1337

The input file contains this single line.

![title](https://styles.redditmedia.com/t5_3r1tmi/styles/communityIcon_1g0st8ztvcc61.png)

**Comment by swsnr** [comment] 2022-12-24 06:53
Can you please fix the formatting of your comment?

I've only skimmed it but the actual error seems to be that images don't get shown in kitty?  If so that's a separate problem; please open a new issue for this.

**Comment by swsnr** [comment] 2022-12-28 20:37
@norman-abramovitz Friendly ping.  Please fix the syntax of your comment; I've hidden it meanwhile.

You might also want to run `mdcat --detect-only` to check what terminal `mdcat` assumes you have, because I presume it's wrong: mdcat has a dedicated kitty backend, and thus shouldn't attempt to print iterm commands to kitty terminals.

**Comment by norman-abramovitz** [comment] 2023-01-03 17:20
Hi,

I was attempting to reproduce the original issue and not introduce a new issue and provide additional information that I found.   I will try the detect-only option when I look at this issue again.

**Comment by swsnr** [comment] 2023-10-18 18:20
Closing this, because it doesn't affect me.

**Closed by swsnr** 2023-10-18 18:20 UTC
Labels: bug, help wanted
